spring:
  application:
    name: testbed
  kafka:
    enable: true
    consumer:
      bootstrap-servers: localhost:9092
      group-id: listener-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      max-poll-interval-ms: 100
      enable-auto-commit: true
      auto-commit-interval-ms: 101

testing:
  mq: ''

active-mq:
  broker-url: tcp://localhost:61616
  topic: ledger-1
  user: admin
  password: admin

kafka:
  topic: ledger-1
  bootstrap: localhost:9092
  group: listener-1
  offset-reset: earliest
  sse-enabled: false

rabbit:
  user: guest
  password: guest
  host: localhost
  port: 5672
  sse-enabled: false

pulsar:
  service-url: pulsar://localhost:6650
  topic: ledger-1
  subscription-name: ledger-sub

server:
  port: 9080
