spring:
  application:
    name: testbed

testing:
  mq: ''

active-mq:
  broker-url: "tcp://localhost:61616"
  topic: "ledger-1"

kafka:
  topic: ledger-1
  bootstrap: localhost:9092
  group: listener-1
  
server:
  port: 9080