spring:
  application:
    name: testbed

testing:
  mq: ''

active-mq:
  broker-url: tcp://localhost:61616
  topic: ledger-1
  user: admin
  password: admin

kafka:
  topic: ledger-1
  bootstrap: localhost:9092
  
pulsar:
  service-url: pulsar://localhost:6650
  topic: ledger-1

server:
  port: 9081