spring:
  application:
    name: testbed

testing:
  mq: ''

active-mq:
  broker-url: tcp://localhost:61616
  topic: ledger-1
  user: admin
  password: admin

kafka:
  topic: ledger-1
  bootstrap: localhost:9092
  sse-enabled: false
  acks: 1
  retries: MAX_INT
  max-in-flight: 5
  
pulsar:
  service-url: pulsar://localhost:6650
  topic: ledger-1

message:
  delivery: at_least_once 

server:
  port: 9081
